name: clean_architecture_posts_app
description: "Posts App with clean architecture"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
   # Bloc for state management
  flutter_bloc: ^9.0.0
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.7
  # Service locator
  get_it: ^8.0.3
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^1.3.0
  # Local cache
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true

   
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

 
